### ISSUE TITLE
What is the current situation of s6 init in Fedora Rawhid project?

### ISSUE THREAD

**Issue by FedoraForever** [dockerimages/fedora-s6#2]
***WARNING***
I sent you an e-mail, I sent you a message here to be more active on Github. Please also read the e-mail I sent!

Hi,
     
 I'm crazy about systemd for tons of reasons. I don't want to explain why.  I use Fedora. But, it uses systemd for default init and it can never be changed.
Finally, I found your project called "fedora-s6" on Github. But the project was completely created 8 years ago (the s6 wasn't even popular.) I looked at the commits, and I saw the 7 commits you made. In the Readme.md file, you mentioned:
       See the enclosed INSTALL file for installation details.
And you have added a dockerfile but the INSTALL file is not there and where are the installation details?. I'm looking forward to installing the s6 init system on Fedora and you are the first to get the s6 running on Fedora. Please explain to me, how did you do this in your Github project? Fedora s6 doesn't support it and how did you break this barrier? Most importantly, where is the INSTALL file? Final question: Why didn't you go ahead with this project and give instructions on how to do it? Project from 2015 and rotten

![github7](https://user-images.githubusercontent.com/69630326/189478273-4ec22371-2a5f-4c47-a3a4-108e3719a11a.png)
A fork of your project.
![github6](https://user-images.githubusercontent.com/69630326/189478276-8c95f38b-7fa4-4f93-9428-f45d72d5b5fa.png)
![github5](https://user-images.githubusercontent.com/69630326/189478277-dc98daac-6768-4ccd-add4-1cd9d543ae6b.png)
Your project's commits. No clue about s6 in Fedora. 
![github4](https://user-images.githubusercontent.com/69630326/189478278-2bd8efb1-6368-477e-aadb-160e6533ffa2.png)
Your project's Docker file. I don't understand why you put.
![github3](https://user-images.githubusercontent.com/69630326/189478280-d26d286c-47f5-44e1-adfa-f498ae2a03e0.png)
A writing by you about installing. But, where is the INSTALL file??? 
![github2](https://user-images.githubusercontent.com/69630326/189478281-d77b2ab0-cd08-4432-bc23-9096b5363419.png)
You said what s6 is but you didn't show the setup?
![github8](https://user-images.githubusercontent.com/69630326/189478567-e901f6a1-a160-4568-8b33-e64b71b6a48f.png)
Your shared files in s6 init in Fedora Rawhid project. No INSTALL file. 
        I left the link of your project link for you to
 remember. It is very exciting to meet a respected business owner like you. Hope you reply...

Your project's Github page: https://github.com/dockerimages/fedora-s6
Your project's on Github Docker file: https://github.com/dockerimages/fedora-s6/blob/master/Dockerfile

                                        ~Fedora user who does not want to be named

**Comment by frank-dspeed** [comment]
I readed it all your wrong as i sayed in the email this is a docker image google the term libcontainer image.

While this is Fedora with s6 init this is not something you can do on your Local Computer.

SystemD is part of your Kernel.

**Comment by FedoraForever** [comment]
Hello, 

Well, I won't try this on my computer. But, how did you run Fedora in Docker with s6 init? I'm just wondering. There is no INSTALL file and how did you do it? (in Docker)

*Thanks for the reply, sorry for my bad English.*

**Comment by frank-dspeed** [comment]
@FedoraForever it is simple you do it like with any other image 
Dockerfile
```
FROM fedora:21
RUN yum install -y git gcc make
RUN mkdir /git.src
WORKDIR /git.src
RUN git clone git://git.skarnet.org/execline
RUN git clone git://git.skarnet.org/s6 
RUN git clone git://git.skarnet.org/skalibs
WORKDIR /git.src/skalibs
RUN ./configure 
RUN make 
RUN make install
WORKDIR /git.src/execline
RUN ./configure 
RUN make 
RUN make install
WORKDIR /git.src/s6
RUN ./configure && make && make install
```

is the Dockerfile you build that with docker it includes everything that is needed
Fedora Version at top, Installing dependencies via yum, then it builds s6 as it is C Code we need to turn that into binary

this installs as you can see execline s6 and skalibs so the whole suite of tools you need to read on the homepage  of s6 and docker manuals how you can do more with that

you should watch this and in the examples replace ubuntu with fedora it will all work.

it does so because every container has its own init system and systemd is not used in containers when  you run them on fedora

https://github.com/just-containers/s6-overlay

**Comment by FedoraForever** [comment]
Thank you. This project is not like I can try on my native Fedora. That would be difficult to do. It's just a long and pointless effort.

**Comment by FedoraForever** [comment]
Thank you. This project is not like I can try on my native Fedora. That
would be difficult to do. It's just a long and pointless effort.

Frank Lemanschik ***@***.***>, 11 Eyl 2022 Paz, 08:49
tarihinde şunu yazdı:

**Comment by hholst80** [comment]
> SystemD is part of your Kernel.

well, that is not correct but the Fedora experience is not going to fly well if you try to rip out systemd from it.  If you are looking for a distro that does not feature systemd you can look at voidlinux.org.

**Comment by frank-dspeed** [comment]
@hholst80 if you want to learn more about the kernel parts of systemd look into systemd boot that's the part that's runs in kernel mode
